# Generated by Django 2.2 on 2020-04-12 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20200411_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_like_dislike', to='posts.Post'),
        ),
    ]
